#!/bin/bash
: '
Personal .profile - Bash Aliases
By: Tim Oram
'

# sometimes I like to quit
alias quit=exit

# color my diff
alias diff=colordiff

# sha1 hash shortcut
alias sha1="openssl sha1"

# hackish get current local ip
alias myip="ifconfig | grep 192"

# ps search
alias apps="ps ax | grep"

# remove directory
alias rd="rm -rf"

# date shortcuts
alias timestamp="date +%s"

# php shortcuts
alias php-vulcan="php -dvld.active=1"
alias phpdoc="php ~/Code/PhpDocumentor/phpdoc"

# editor
__compat "OSX" 'alias e="edit"'
__compat "Linux" 'alias e="vim"'

# komodo
__compat "OSX" "alias k=\"open -a 'Komodo IDE'\""

# profile
alias .p=". ~/.profile"

# quick edits
alias e.hosts="edit /etc/hosts"
alias e.p="e ~/.profile"
__compat "OSX" 'alias e.vhosts="e /usr/local/etc/nginx/vhosts-available/"'
__compat "OSX" 'alias e.nginx="e /usr/local/etc/nginx/nginx.conf"'
alias e.includes="e ~/.bash_includes.d"
alias e.gitconfig="e ~/.gitconfig"
alias e.etc="e /usr/local/etc"
alias e.bin="e ~/bin"
alias e.ssh="e ~/.ssh/config"

# git achievements
if [ `type -t git-achievements` ]; then
    alias git="git-achievements"
else
    __DEBUG_MESSAGE "git-achievements not found, disabling."
fi
# logs
__compat "OSX" 'alias nlog="tail -f -n50 /usr/local/var/logs/nginx/error.log"'

# Add colors to ls, grep
__compat "OSX" "alias ls='$(brew --prefix coreutils)/bin/gls --color'"
__compat "Linux" "alias ls='ls --color'"
alias grep='grep --color=auto'

# json pretty
alias json="python -mjson.tool"

# url encoder
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'

# strip most html tags
alias striptags="sed -e :a -e 's/<[^>]*>//g;/</N;//ba'"

# clear alias
alias c=clear

