#!/bin/bash

: '
Personal .profile - Common functions
By: Tim Oram
'

source_all() {
	while [ $# -gt 0 ]
	do
		. "$1"
		shift
	done
}

new_random_number() {
	local min=${1:-0}
	local max=${2:-32767}
	
	# See if the min and max are reversed, if so reverse
	if [ ${min} -gt ${max} ]; then
		local x=${min}
		min=${max}
		max=${x}
	fi
	RAND=$((RANDOM%max+min))
}

__compat() {
	
	local os=$(uname);
	
	if [[ "$os" == "Darwin" ]]; then
		os="OSX"
	fi
	# check os matches filter provided in $1
	if [[ $(echo $1 | grep $os) ]]; then
		shift
		eval "$*"
	fi
}

__DEBUG_MESSAGE() {
	if ( ${__PROFILE_DEBUG:-""} ); then
		echo "$*"
	fi
}
