#!/bin/bash

: '
Personal .profile - PATH setup
By: Tim Oram
#'

# Homebrew, mostly
__compat "OSX" "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/share/python:$PATH"

# extra git commands
__compat "OSX" "PATH=/usr/local/Cellar/git/1.7.4.1/libexec/git-core:$PATH"
__compat "Linux" "PATH=/usr/lib/git-core:$PATH"

# personal bin
PATH=~/bin:$PATH

# git achievements path
PATH=~/bin/git-achievements:$PATH

export PATH