#!/bin/bash
: '
Tasks Switcher
A task list switcher for `t`

See: https://github.com/MitMaro/tasks

By: Tim Oram
#'

# set some defaults
__TASKS_T_PATH=${__TASKS_T_PATH:-~/bin/t/t.py}
__TASKS_LIST_DIR=${__TASKS_LIST_DIR:-"~/.tasks"}
__TASKS_LIST_FILE=${__TASKS_LIST_FILE:-"tasks"}
__TASK_CURRENT_LIST_FILE=${__TASK_CURRENT_LIST_FILE:-".current_task_list"}

__TASKS_SHOW_PROBABILITY=${__TASKS_SHOW_PROBABILITY:-"10"} # note this is 10 not -10

__TASKS_DEFAULT_COUNT_COLOR=${__TASKS_DEFAULT_COUNT_COLOR:-"\033[1;37m"}
__TASKS_LOW_COUNT_COLOR=${__TASKS_LOW_COUNT_COLOR:-"\033[0;32m"}
__TASKS_MEDIUM_COUNT_COLOR=${__TASKS_MEDIUM_COUNT_COLOR:-"\033[1;33m"}
__TASKS_HIGH_COUNT_COLOR=${__TASKS_HIGH_COUNT_COLOR:-"\033[0;31m"}
__TASKS_NAME_COLOR=${__TASKS_NAME_COLOR:-"\033[1;33m"}
__TASKS_COLOR_NORMAL=${__TASKS_COLOR_NORMAL:-"\033[0;37m"}
__TASKS_COLOR_RESET=${__TASKS_COLOR_RESET:-"\033[0m"}

__TASKS_LOW_COUNT_LIMIT=${__TASKS_LOW_COUNT_LIMIT:-"2"}
__TASKS_MEDIUM_COUNT_LIMIT=${__TASKS_MEDIUM_COUNT_LIMIT:-"6"}
__TASKS_HIGH_COUNT_LIMIT=${__TASKS_HIGH_COUNT_LIMIT:-"14"}

__TASK_PS1_PREFIX=${__TASK_PS1_PREFIX:-"  ("}
__TASK_PS1_POSTFIX=${__TASK_PS1_POSTFIX:-")"}

__TASK_PROMPT_PREFIX=${__TASK_PROMPT_PREFIX:-"\n"}
__TASK_PROMPT_POSTFIX=${__TASK_PROMPT_POSTFIX:-"\n"}

# only load tasks if found
if [ -f "$__TASKS_T_PATH" ]; then

# task list switcher/creator
tasks () {
	
	# if tasks directory does not exist create it, but check for a file
	if [ -f "$__TASKS_LIST_DIR" ]; then
		echo "__TASKS_LIST_DIR is a file, needs to be a directory"
	elif [ ! -d "$__TASKS_LIST_DIR" ]; then
		echo "Creating task directory: $__TASKS_LIST_DIR";
		mkdir "$__TASKS_LIST_DIR"
	fi
	
	# list tasks
	if [ "$1" == "-l" ]; then
		ls -1 $__TASKS_LIST_DIR
		return
	# simple help message
	elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
		echo "usage: tasks [name]"
		echo "       tasks -l"
		echo "       tasks -h"
		echo
		echo "Options:"
		echo " name  The name of a task list"
		echo " -l    List all task lists available"
		echo " -h    Show this message"
		echo ""
	# set current task list to the saved task
	elif [ "$1" == "" ]; then
		
		# if there is no current task file we just exit, doing nothing
		if [ ! -f "$__TASKS_LIST_DIR/$__TASK_CURRENT_LIST_FILE" ]; then
			return
		fi
		
		export __TASKS_LIST_FILE=`cat $__TASKS_LIST_DIR/$__TASK_CURRENT_LIST_FILE`
	# switch the task list
	else
		# if a new task file
		if [ ! -f "$__TASKS_LIST_DIR/$1" ]; then
			
			# prompt to create new list, return on no 
			read -n1 -p"List does not exists. Create? [y|N] " REPLY
			echo
			if [[ $REPLY != [yY] ]]; then
				return
			fi
		fi
		
		# set the task list file
		export __TASKS_LIST_FILE="$1"
		
		# save the current task file to a file
		echo $__TASKS_LIST_FILE > $__TASKS_LIST_DIR/$__TASK_CURRENT_LIST_FILE
	fi
	
	# create/update the alias
	alias t='python $__TASKS_T_PATH --task-dir $__TASKS_LIST_DIR --list $__TASKS_LIST_FILE $__TASKS_T_ARGS'
}

# load the default saved task list when this file is loaded
tasks

else
	__DEBUG_MESSAGE "tasks not found, skipping.";
fi

